sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
language: java
env: PLAY2_HOME=$TRAVIS_BUILD_DIR/org.opencompare/play-app/
jdk:
  - openjdk8

script: cd org.opencompare/ && mvn clean install
